### ISSUE TITLE
case insensitive tab completion

### ISSUE THREAD

**Issue by TorchedSammy** [reeflective/readline#25]

**Comment by maxlandon** [comment]
An upcoming release is going to provide full `.inputrc` support for keybinds.
I had forgot to tell you about it: don't bother trying to interface with the current version of the library,
especially keybinds; the API for them is going to change. Things like completions, history and hints won't change
though, they are stable now.

For your issue: case insensitivity will be possible in the upcoming release (a matter of days).

**Comment by maxlandon** [comment]
Learning the `.inputrc` configuration file, if you haven't already, will save you a lot of time when setting your binds to the readline console.

**Comment by maxlandon** [comment]
Hello Sammy,
I've just push a bunch of commits and will soon release the new version of the library, which supports `.inputrc` keybinds, as told previously.

About case-insentive completion: this is not handled by the library. When you will populate the `readline.Completions` type with one of the various
provided functions/methods (see `completions.go`), you will be responsible of filtering candidate against the current prefix. This is so that it's
both easier for most people and more powerful for people who want to check/set more custom logic.

I'm thus closing this issue, but don't hesitate reopening it (or creating a new one) if you need

**Comment by maxlandon** [comment]
Following recent fixes and changes to the completion system, the latter accepts an inputrc `completion-ignore-case` which, if set to `on`, will not filter candidates in case-sensitive way.
